# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/amd64-base-python:3.10-alpine3.18"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.10-alpine3.18"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.10-alpine3.18"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.10-alpine3.18"
  i386: "ghcr.io/home-assistant/i386-base-python:3.10-alpine3.18"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Baby sleep tracker"
  org.opencontainers.image.description: "Track your baby sleep times."
  org.opencontainers.image.source: "https://github.com/erhanbaris/"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"